name: Flask CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask application
      run: |
        export FLASK_APP=app.py
        nohup flask run &  # Run Flask in the background
        sleep 10  # Allow Flask some time to start

    - name: Run tests
      run: |
        python -m unittest discover -s tests

    # Commented out deployment steps
    # - name: Deploy to staging
    #   if: github.ref == 'refs/heads/dev'
    #   run: |
    #     # Deployment steps for staging

    # - name: Deploy to production
    #   if: github.ref == 'refs/heads/main'
    #   run: |
    #     # Deployment steps for production

    # Commented out notification steps
    # - name: Send email notification
    #   run: |
    #     echo "Sending email notification"
    #     python -c "
    # import smtplib
    # from email.mime.text import MIMEText
    # from email.mime.multipart import MIMEMultipart

    # email = '${{ secrets.EMAIL_ADDRESS }}'
    # password = '${{ secrets.EMAIL_PASSWORD }}'
    # recipient = 'gombedlm@mail.uc.edu'

    # subject = 'HomeGuard CI/CD Pipeline Notification'
    # body = 'The CI/CD pipeline for HomeGuard has completed successfully.'

    # msg = MIMEMultipart()
    # msg['From'] = email
    # msg['To'] = recipient
    # msg['Subject'] = subject

    # msg.attach(MIMEText(body, 'plain'))

    # server = smtplib.SMTP('smtp.gmail.com', 587)
    # server.starttls()
    # server.login(email, password)
    # text = msg.as_string()
    # server.sendmail(email, recipient, text)
    # server.quit()
    # "
