name: HomeGuard CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: homeguard_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      PYTHONPATH: "src"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask migrations (if any)
        run: |
          flask db upgrade

      - name: Run tests
        run: |
          pytest

      - name: Collect static files (if applicable)
        run: |
          flask collectstatic --noinput

      # Add deployment steps here if needed

      # Add notification steps here if needed


